### ISSUE TITLE
Add Planetary Approach Suite

### ISSUE THREAD

**Issue by cmdrmcdonald** [cmmcleod/coriolis-data#9]
The planetary approach suite is not a lot of use to show in Coriolis itself (although it does have a cost), but is useful to have for downstream systems that use Coriolis as an authoritative source of data for modules.  Please could it be added in?

Possible planetary_approach_suite.json (with correct ED ID)

```
{
  "pas": [
    { "id": "PA", "edID": 128672317, "eddbID": null, "grp": "pas", "class": 1, "rating": "I", "cost": 500, "power": 0.0, "mass": 0 }
  ]
}
```

**Comment by cmmcleod** [comment]
Yes absolutely.

**Comment by cmmcleod** [comment]
I'm also going to clean up the JSON schema/structure of all of the standard modules to be the same as everything else. i.e

```
{
   "[Standard Group Code]": [
       {...}, {...}, ... {...}
   ];
}
```
